; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps = 
	rfetick/MPU6050_light@^1.1.0
	waspinator/AccelStepper@^1.64
monitor_speed = 115200

[env:robot_firmware]
build_src_filter = +<robot_main/> -<calibration/> -<test_code/>

[env:mpu_calibrate]
build_src_filter = -<robot_main/> +<calibration/> -<test_code/>

[env:test_code]
build_src_filter = -<robot_main/> -<calibration/> +<test_code/>
